### ISSUE TITLE
Support for video cutscenes

### ISSUE THREAD

**Issue by Siphonay** [NVIDIA/Q2RTX#11]
As Q2RTX is based on Q2PRO, support for game cutscenes is not present. Would it be feasible to implement them in order to allow those like me who would like to play through the game casually with insight of what's happening in the story?

**Comment by apanteleev** [comment]
It's unlikely that we will add support for video cutscenes. Looks like there might be a significant amount of work necessary for that, with relatively small effect on the game overall.
But if someone implements it, we'll be happy to merge.

**Comment by jonnypanic** [comment]
I hope someone does implement it. I disagree that the effect is small (though yeah I don't know how much work is involved). I just played through the campaign and without the cutscenes there isn't much to explain what you're supposed to be doing. Obviously there isn't much story in this game but it feels incomplete without them.

**Comment by josestefan** [comment]
vkQuake2 has the cutscenes support, I think. Would that help?

**Comment by CKWarner** [comment]
It probably wouldn't be a lot of work to put support for the cutscenes back in. Originally they'd get chainloaded with a level change as somevideofile.cin+somelevelname.bsp in SV_Map, which runs the cinematic and then loads the level. Q2PRO and Q2RTX include a specific test, SV_ParseMapCmd that throws away everything before the +. You'd need to take that out and then include the ss_cinematic stuff from either the original release or vkQuake2.

**Comment by CKWarner** [comment]
There's a description of the .cin format [here](https://multimedia.cx/mirror/idcin.html), and - as far as I can tell - the original Quake 2 decoder was [this](https://github.com/id-Software/Quake-2/blob/master/client/cl_cin.c), in case that helps anyone to find the parts that need adding.

**Comment by SkacikPL** [comment]
First half of the cinematics code is not that hard to port but 2nd half relies on passing stuff to vulkan and there are obvious differences in design between Q2RTX and vkQ2 which i can't really chew since i'm both not familiar with the renderer and i'm not really a competent programmer, especially with C.

But i can't imagine that porting it from vkQ2 would be too hard for NVIDIA guys, given 3/4 of stuff can be lifted off vkQ2 with only slight alterations, bulk of the work lies with making sure it works with the renderer which they're well familiar with.

**Comment by CKWarner** [comment]
I hope so, too. It's the main thing that's missing from the release.

I _think_ that the way it's been done, generally, is to decode the .cin file into a series of .pcx files and then draw them one after the other. Both Q2RTX and vkQ2 seem to have similarly-structured functions to draw a resized image to the screen. Maybe that will help.

**Comment by kondrak** [comment]
Adding cinematics support was fairly trivial in case of vkQuake2 - the decoded frames were fed directly by the client code via the `SCR_DrawCinematic()` in `cl_cin.c` which in turn called renderer-specific implementation of `Draw_StretchRaw()` - all I had to do was write a Vulkan version of that function: https://github.com/kondrak/vkQuake2/blob/master/ref_vk/vk_draw.c#L245

Since the data was already decoded, my work was limited to properly updating the image buffer holding the current frame - this same function is also being used for "static cutescenes", such as the infamous "THE END" screen. Note however that vkQuake2 uses the original structure and no major modifications to "higher-level" client code had been done, so if that part changed significantly it might be in fact quite some work to get this working in Q2RTX.

**Comment by SkacikPL** [comment]
As far as i can tell, the "client" part is not really an issue. There are however differences in how Vulkan renderer is laid out in vkQ2 and Q2RTX which i personally didn't jump past at the moment.

If someone is competent with Vulkan, it shouldn't be a problem to port over the actual drawing part.

At the moment Q2Pro/Q2RTX pretty much stubs out the entire cutscene system and strips out the functionality, like the cinematic+map syntax. Though that can easily be restored and beyond that at client level of things it shouldn't have any real issues.

**Comment by kondrak** [comment]
I just had a quick look at Q2Pro code and it's strange that they did this. I'm sure there must've been a reason behind it or maybe there was not enough pressure from the Q2Pro community? :)

**Comment by SkacikPL** [comment]
It's obvious when you consider what Q2Pro was intended to be - a multiplayer centric source port.
The sole fact it runs SP at all is a bonus, even though as far as i can tell it's just a copy of OG source code with bare minimum added to interface with the client. For instance Yamagi versions of base game and expansions contain bunch of fixes to the original code to make the experience better.

Q2Pro was a poor choice to host Q2RTX if it was supposed to be a SP-centric "remaster" (as in actual playable game) since Q2VKPT only used it because it was barebones and it considered itself POC tech demo. Then again, at this point it's probably pointless to rebase entire thing to a more competent SP client like Yamagi.

**Comment by apanteleev** [comment]
Implemented in https://github.com/NVIDIA/Q2RTX/commit/9bac58e11163b0e837b3f6314c69fda88bcb8abb

**Comment by CKWarner** [comment]
> Implemented in [9bac58e](https://github.com/NVIDIA/Q2RTX/commit/9bac58e11163b0e837b3f6314c69fda88bcb8abb)

That's great news!

**Comment by Siphonay** [comment]
Awesom, thank you so much!

**Comment by thegreatestminer** [comment]
@Siphonay, you can close the issue now.

**Comment by Siphonay** [comment]
> 
> 
> Implemented in [9bac58e](https://github.com/NVIDIA/Q2RTX/commit/9bac58e11163b0e837b3f6314c69fda88bcb8abb)

**Comment by antdude** [comment]
Is this fix out in the compiled version?

**Comment by apanteleev** [comment]
> Is this fix out in the compiled version?

Yes, it has been there since v1.3.

**Comment by antdude** [comment]
Hmm. Don't see it from Steam's version in Linux/Debian.

**Comment by apanteleev** [comment]
Do you have the `*.cin` files in `baseq2/video` ?

**Comment by antdude** [comment]
Yes from the full game Bethesda.net Launcher's last year's free digital giveaway copy (copied from a decade old 64-W7 HPE SP1 PC):

19,311,290 end.cin
 6,038,210 eou1_.cin
 6,586,381 eou2_.cin
 6,708,418 eou3_.cin
 5,464,002 eou4_.cin
 6,848,133 eou5_.cin
 7,099,332 eou6_.cin
 7,766,671 eou7_.cin
11,875,656 eou8_.cin
 3,159,828 idlog.cin
82,836,235 ntro.cin
163,694,156 bytes

Also, shareware didn't work too.

**Comment by apanteleev** [comment]
The last thing I can think of is the `cl_cinematics` console variable, which should be set to 1 for the videos to play.
Beyond that, check your game logs or try debugging it...
