### ISSUE TITLE
Saved games doesn't work after update to 1.6.0

### ISSUE THREAD

**Issue by mistificator** [NVIDIA/Q2RTX#178]
I've updated from 1.5.0 to 1.6.0 yesterday (I use Steam), and got these messages.
![image](https://user-images.githubusercontent.com/2280081/150647621-a2ef8e62-8f67-4db9-b544-7170cec4af04.png)

**Comment by mistificator** [comment]
Workaround is to take old gamex86_64.dll from 1.5.0.

**Comment by Paril** [comment]
You can use the old game DLL, but this is to be expected with Q2-based games. Save games will break between major game DLL version changes.

There were some legacy bugs fixed between the two, hence the version change.

**Comment by mistificator** [comment]
So you think that in-game progress is nothing. Okay I see your point.

**Comment by Paril** [comment]
> So you think that in-game progress is nothing. Okay I see your point.

This is just how it was in Quake II. You're free to contact John Carmack and let him know you don't like his 15+ year old decisions. We did inherit some pointer-esque fixes from Q2PRO but because the save format is extremely basic and basically just writes the raw memory to disk, this is bound to happen. It's out of the scope of Q2RTX to introduce a new save system, IMO. You should file an issue with Q2PRO instead; if they adopt one, Q2RTX will inherit it.

**Comment by res2k** [comment]
@mistificator I attempted to add savegame compatibility for 1.5.0 in PR #193. It seems to work, but I gave it only a quick test, so maybe give it a try. You should be able to open savegames from 1.5.0, and after re-saving they'll be in the updated format. (Note this doesn't work in the other direction: savegames created with 1.6.0 will never work in 1.5.0.)

**Comment by apanteleev** [comment]
PR #193 is now merged, which should take care of this issue.
