### ISSUE TITLE
2D Explosions? No Smoke? It's time for some pull requests!

### ISSUE THREAD

**Issue by dagelf** [NVIDIA/Q2RTX#183]
It's quite sad that the purest raytracing game still has 2D explosions. This is ray traced! How hard can it be? Perhaps start with smoke and a better railgun effect, and then work our way up from there?

**Comment by Beilerbey** [comment]
https://github.com/NVIDIA/Q2RTX/issues/33

**Comment by Paril** [comment]
Finding people with relevant Vulkan experience willing to contribute to a Quake II-based open source project is a niche of a niche of a niche of a niche. If you know people who would be interested, bring 'em here, but we'll likely just be stuck with 2D sprites otherwise.

**Comment by res2k** [comment]
FWIW, you get the "old" explosion models back with `set cl_explosion_sprites 0`. I personally prefer them since they look more "3D", but it's in other aspects less detailed than the 2D sprites and certainly no "volumetric" effect.

And BTW, volumetric smoke/explosions are _hard_. See here: https://pbr-book.org/3ed-2018/Light_Transport_II_Volume_Rendering for an idea of what's involved. And that's for "offline" rendering only, realtime ray tracing needs layers of trickery.

**Comment by apanteleev** [comment]
> How hard can it be?

Pretty hard, if you want the result to look natural and still be real time.

Closing the issue as not constructive.

**Comment by dagelf** [comment]
Come on. Fog?! I will give it a bash and I bet it can be done in less than
10 lines of code.... during my next holiday. Unless someone beats me to it.

**Comment by apanteleev** [comment]
Simple unlit fog is implemented (see https://github.com/NVIDIA/Q2RTX/issues/132) - and it is unlit precisely because lighting the fog with many lights is non-trivial.

Explosions and smoke are more complicated than fog because they are more dense, therefore need more accurate lighting, and then there's fluid simulation.

**Comment by dagelf** [comment]
Some inspiration:

![image](https://user-images.githubusercontent.com/802628/155424223-12f8e286-2ca4-436f-a8bc-6a3296234180.png)
https://www.shadertoy.com/view/Xss3DS

![image](https://user-images.githubusercontent.com/802628/155424266-41c6c3d0-fb16-48ef-9e1c-f28739e8aa48.png)
https://www.shadertoy.com/view/4lfSzs

![image](https://user-images.githubusercontent.com/802628/155424329-e21b11ce-9766-4a5f-8c68-fdabc9525c98.png)
https://www.shadertoy.com/view/lsySzd

![image](https://user-images.githubusercontent.com/802628/155424378-7527b7b8-bd87-429b-b031-75e340b71e28.png)
https://www.shadertoy.com/view/4sByWz

**Comment by res2k** [comment]
Clearly this is a topic you're quite passionate about. Since the Q2RTX code base is open source I suggest you go and try your hand. In the best case this would result in an improvement to Q2RTX, but in any case, you'll gain practical experience and knowledge.
