### ISSUE TITLE
[Question] About existing server exploits for Quake 2

### ISSUE THREAD

**Issue by RoLex** [NVIDIA/Q2RTX#186]
Hi.

Maybe a stupid question, but I need to make sure before I open my Quake 2 server to open world.

There are known public exploits available for different server versions, such as:

https://www.exploit-db.com/exploits/19079
https://www.exploit-db.com/exploits/21450
https://www.exploit-db.com/exploits/24710

Since I could not locate the Quake 2 version Q2RTX is based on, I'm no longer sure if these exploits are covered by your release?

I will be running on Windows Server 2016 version 1607.

Regards.

**Comment by res2k** [comment]
Q2RTX is based on Q2PRO. Specifically Q2RTX 1.6.0 contains the Q2PRO changed up to Git commit f4b7b6786a8d5672a35ed59f4e66c77fe6f321aa.
It's very, very likely these exploits are fixed in the Q2PRO codebase, but if you want to be certain you could ask over there.

**Comment by RoLex** [comment]
@res2k 

Thank you. I'll check with them!

**Comment by Paril** [comment]
Hi there @RoLex - I can answer most of these.

The first exploit is from the 3.14 era, and were patched by id Software.
The second exploit is part of vanilla 3.20, but was patched by other source ports - in Q2PRO, cvars can be marked as PRIVATE, which prevents them from being token-expanded. The fix in the security notes prevents *all* cvars from being expanded, which isn't ideal because servers (ab)use this to get info from the client (like their version).
The third is an old bug related to the `download` command. Unfortunately the original bugtraq link is dead, but if you look via web archive ( http://web.archive.org/web/20200228162125/https://www.securityfocus.com/bid/11551/exploit ) you can see how it was exploited: you could just `download` random files this way, which was used by the connection process, but early on this could be exploited to download things like autoexec.cfg/config.cfg to get rcon password. This was also patched by every major source port (and I think 3.20 itself).

**Comment by RoLex** [comment]
@Paril

Thank you for detailed answers!
