### ISSUE TITLE
Documentation mapping/modding

### ISSUE THREAD

**Issue by enigma7483** [NVIDIA/Q2RTX#27]
Are there any plans to document map making and modding/textures/materials for this build of the q2 engine?   Not really an issue this just makes me want to get back into mapping and modding and any documentation that we could get would help take the guess work out of things

**Comment by SkacikPL** [comment]
Materials seems straightforward enough you need the high resolution texture with normal map ("_n") and light map for emissive surfaces then define its params in materials.csv according to order in first line.

Defining lava and non-actual skybox sky pieces "should" work as following, you look at that element and do /echo $cl_clusterthere which should print number of cluster for that element which then can be written down to the sky_clusters.txt file.

At least that's as much as i have figured out as of now.

**Comment by CKWarner** [comment]
To add to that, looking at the sky_clusters.txt file will show that lava is not emissive by default. If a level has lava, you can make it glow automatically by adding !all_lava to that level's entry in sky_clusters.txt. Otherwise, you can pick and choose which lava elements should glow.

**Comment by SkacikPL** [comment]
To my understanding sky lighting is considered on global scale, meaning that even if there's a piece of skybox placed near window, it's treated as if its light was casted from far away and as such its influence through relatively small window (compared to open sky) is small and it might need a boost. In any case of sky being used in closed spaces (windows, skylights, etc.) each of those needs to be flagged in sky_clusters.txt

I checked which exactly clusters NVIDIA flagged in original maps and it's always the cluster with the sky, not the cluster where light bleeds in or ones affected by it. This also means you cannot look at sky and use /echo $cl_clusterthere while looking at sky but instead need to use noclip, get as close to it as possible without actually being IN the sky and use /echo $cl_cluster.

If it returns -1 it means you're in the sky and need to back off a little. Also large segments will most likely have more than 2 cluster so you need to check all corners to see whether you got all of the clusters for given light source.

Within the file it seems the clusters are numbered from smallest number to highest and it's one line per light source.

**Comment by CKWarner** [comment]
I don't know if this will help with your skybox investigations, but the Quake 2 maps are [Binary Space Partitions](https://en.wikipedia.org/wiki/Binary_space_partitioning) - it's literally their name - to define [Potentially Visible Sets](https://en.wikipedia.org/wiki/Potentially_visible_set).

You can see from wandering around with noclip on that the levels are divided into regions of visibility: areas simply aren't drawn unless you're in a part of the map where you would normally be able to (potentially) see them.

I think that what you're doing with putting the skybox in sky_clusters.txt is saying "these are potentially visible everywhere," and should be used for the light calculations, since they won't be otherwise.

**Comment by apanteleev** [comment]
We do plan to release a modding guide, yes.

A couple notes regarding the sky cluster tagging:

1) All sky and lava are always emissive. The difference between those sky/lava polygons that are marked in the clusters file and those which are not is which tracing pass collects their illumination:

- If a sky/lava polygon is listed in the file, it will be converted into an analytic light, just like regular lamps found everywhere. The direct lighting shader collects illumination from those, and it's not very noisy - unless there are fewer than 100 (ish) light triangles visible from a cluster. As a bonus, you get one extra bounce of sky/lava lighting this way.

- If a polygon is NOT listed in the file, its illumination will be collected by the indirect lighting shader, should an indirect ray happen to hit that polygon. This is free and doesn't affect direct lights, but it does produce more noise when the visible area of the sky/lava is small.

As a rule of thumb, small windows in otherwise dark rooms should be marked in the file. Large sky boxes around open areas should not, as that would create too many light triangles, and the direct lighting denoiser wouldn't be handle that noise. Small patches of lava in caves should also be marked in the file, which will add one extra bounce of lava illumination.

2) In order to see the sky polygons and identify clusters, you can edit the `primary_rays.rgen` shader and switch the condition on lines 108-109: `if((!found_intersection(ray_payload_brdf) || is_sky(ray_payload_brdf)) && !is_gradient)`. Also, the `draw` command is useful: `draw cl_clusterthere 0 0` will show the cluster you're pointing at in the top-left corner. `draw cl_lightpolys 0 10` will show the number of direct light triangles visible from a surface.

There is also the "light flag" in the `materials.csv` table that tells the engine if the geometry with a certain texture should be converted to analytic lights. Same rules: small and bright things should be analytic, large and dim should not.

**Comment by apanteleev** [comment]
I figured that modifying the source code every time you need to look for clusters is inconvenient, and added a cvar `pt_show_sky`: https://github.com/NVIDIA/Q2RTX/commit/b21f21dc5fc5534fd759224f191f94f1e0f58bd1

**Comment by SkacikPL** [comment]
Another thing regarding lighting is that in the long run some areas (especially in expansions) are really dark and flares are kind of too tedious to use for actual gameplay so i'd suggest adding a flashlight IF the support expansions is to be added in (got a pending pull request #28 for that).

I have a simple cvar based one that does the job. Ideally i wanted it to be a cone light however it seems that directional lights only existed in original renderer and non-dynamic lights.

**Comment by SkacikPL** [comment]
Also something i encountered in the expansion levels is placing sky as a mean of generating "sourceless" light within the level.

![pt_show_sky 0](https://user-images.githubusercontent.com/8530514/60472779-7979c280-9c6a-11e9-8f03-36579332fb37.png)

![pt_show_sky 1](https://user-images.githubusercontent.com/8530514/60472778-7979c280-9c6a-11e9-91fb-a08341c92cd3.png)

Is there any way to skip them as they're generally not needed in the RTX renderer or at least mark them as nodraw?

**Comment by apanteleev** [comment]
Yes - try the `pt_enable_nodraw` cvar. Those sky boxes in expansions are marked with the `SURF_NODRAW` flag, and that cvar makes the renderer ignore such surfaces. But in some maps in baseq2, some legit sky boxes also have the nodraw flag set...

You can set cvars per-map in the `maps/<name>.cfg` files.

**Comment by SkacikPL** [comment]
Yeah, i can confirm that using ``set pt_enable_nodraw 1`` in ``maps/<name>.cfg`` does fix those skybox hacks.

![pt_enable_nodraw 1](https://user-images.githubusercontent.com/8530514/60531975-821ad900-9cfc-11e9-93a6-ac14d5964b69.png)

**Comment by SkacikPL** [comment]
On a semi related note, i noticed that material definitions table is ordered and the system clearly cares about ordering as it shows that "fast search" is disabled once i add new entries.

Is there an easy way to order entries correctly?

**Comment by apanteleev** [comment]
The entries are supposed to be sorted in alphabetical order, by texture name.

**Comment by SkacikPL** [comment]
By texture name do you mean specifically _just_ the texture name, eg. ``dead1`` or entire path like ``models/deadbods/dude/dead1``

**Comment by apanteleev** [comment]
The entire path.

**Comment by SkacikPL** [comment]
Alright thanks for the info.
For ease of use and as reference for others, this online tool:
https://textmechanic.com/text-tools/basic-text-tools/sort-text-lines/

Works great when using comma as delimiter.

**Comment by apanteleev** [comment]
MS Excel works great for editing CSV files, with sorting, filtering and all that. I suppose its open source equivalents should work well too.

**Comment by CKWarner** [comment]
Meh. You could just use awk.

**Comment by SkacikPL** [comment]
Looking at the list of materials i see that at the very least most of them are conforming, expansions and some mods (like zaero) also tried to stick to that convention so it might be worthy to implement name based shader assignment.

Here's my crude attempt:
https://github.com/SkacikPL/Q2RTX/commit/6b3df6cac613a83dddb6921f0e9250af23821c74

Of course it's just an semi educated guesswork but i still think it would greatly increase out of the box compatibility with mods or just custom maps with custom textures. If anything goes wrong, you user will have to manually assign couple of wrongly assigned materials rather than having to manually assign them all.
