### ISSUE TITLE
Transparency limitation/bug?

### ISSUE THREAD

**Issue by SkacikPL** [NVIDIA/Q2RTX#32]
Something i noticed today and i'm not sure whether it's the tech limitation or a bug where having line of sight on transparent object through another transparent object will fail to render the second object.

Water pool is visible when viewed directly.
![Quake 2 RTX Remaster Screenshot 2019 07 03 - 00 44 52 61](https://user-images.githubusercontent.com/8530514/60551615-1f413600-9d2c-11e9-9495-cce917e7b817.png)

Water pool is entirely invisible when viewed through glass panel.
![Quake 2 RTX Remaster Screenshot 2019 07 03 - 00 45 18 63](https://user-images.githubusercontent.com/8530514/60551627-29fbcb00-9d2c-11e9-9bca-03f132f41322.png)

Another example with glass planel positioned between first panel and the pillar.
![Quake 2 RTX Remaster Screenshot 2019 07 03 - 00 51 24 87](https://user-images.githubusercontent.com/8530514/60551786-befec400-9d2c-11e9-92de-919dd2afd831.png)

Pillar behind second panel is visible whilst panel itself is not.
![Quake 2 RTX Remaster Screenshot 2019 07 03 - 00 51 32 75](https://user-images.githubusercontent.com/8530514/60551800-cc1bb300-9d2c-11e9-9130-fa46661d5a97.png)

**Comment by apanteleev** [comment]
Tech limitation, sort of. The reflection/refraction rays ignore the transparent geometry completely, for two reasons: 1) because there is no reflection/refraction processing beyond the first hit; 2) to avoid self-intersection of those rays with the original transparent surface.

If we had a loop over transparent surfaces in the path tracer, two bad things would happen: 1) performance would be significantly worse, because any shader that has a loop over ray tracing calls is just slow due to how the compiler currently handles that; 2) the checkerboarded rendering of reflected and refracted surfaces would no longer work properly because there will be more than 2 opaque surfaces contributing to a given pixel.

**Comment by SkacikPL** [comment]
I had a feeling it would be something along these lines.
It's a shame because with glass panels it's relatively hard to spot unless you're deliberately looking for it, however removing bodies of water entirely makes certain places stick out.

I'm not sure whether it's possible but perhaps "secondary" hit on water could treat it as opaque surface so there's at least a dummy surface even if it lacks its properties?

**Comment by ileile** [comment]
hope this can be resolved.

**Comment by apanteleev** [comment]
The multi-layer transparency situation has been improved in v1.2. It won't look entirely accurate past the first layer, but at least the surfaces are no longer missing if reflection/refraction depth is set to a sufficiently high value.
