### ISSUE TITLE
Nvidia Flow support and particle enhancements.

### ISSUE THREAD

**Issue by CKWarner** [NVIDIA/Q2RTX#33]
In [one of the announcement articles](https://www.nvidia.com/en-gb/geforce/news/quake-ii-rtx-ray-tracing-vulkan-vkray-geforce-rtx/) for Quake 2 RTX it was said that there would be 

> optional NVIDIA Flow fire, smoke and particle effects

As far as I can tell, that hasn't made it into the release.

Those chunky 3D explosions and impact-smoke effects that Quake 2 uses could look a whole lot better if they used something like that instead. The same is true of the particle trails from the weapons.

The projectiles themselves for the blaster and hyperblaster could also be significantly better than the opaque rods they were initially implemented as in 1997.

**Comment by SkacikPL** [comment]
They were shown during the demo with Jensen Huang for Rocket Launcher explosions and BFG effect.
Funnily enough it seems that "enhanced" particles we ended up with are captured renders of at least some of those effects.

I assume it's a mix of having to interface your stuff with C, creating assets and additional performance cost which in the end on the net of pros and cons meant it had to be scrapped.

Same goes for other NVIDIA stuff like Ansel - there was no reason to not implement it, especially since it now can have controls for RT parameters to "overdrive" them for screenshotting purposes.

Another thing that might've been kind of a missed opportunity is not having the VRWorks Audio:
https://www.youtube.com/watch?v=Ozhywx2YbzM

Then it would've been truly a fully path traced game.

**Comment by CKWarner** [comment]
I would assume a performance hit, too, although it does say _optional_.

Being able to do that, in C, in Vulkan, would be a great way for Nvidia to show off, I would think.

**Comment by Lt-47** [comment]
It's weird to remove an effect for performance reason when making a tech showcase. And we've seen the thing run fine in a controlled environment. Then again as far as I know there has been zero use of Nvidia Flow since it's reveal. Maybe it's really that expensive/unstable

**Comment by CKWarner** [comment]
We won't know the reason it was pulled till someone from Nvidia tells us, of course.

It could just as easily be that they don't want anyone finding out how to use Nvidia Flow without signing an NDA, which would be a shame.

**Comment by SkacikPL** [comment]
Yeah it probably has to do with "licensing" where most of their proprietary stuff is already available but only if you're an registered NVIDIA developer but to put it in Q2, they'd need to open the lid on those things entirely without any restrictions.

That's also why there's no Steam API integration, because it's also only semi open source where you get access to it after registering and accepting their terms.

**Comment by CKWarner** [comment]
Even if they don't want to GPL an implementation of Nvidia Flow, they have the old PhysX Particles & Fluid, and I understand that's been released under the BSD licence now. No licence conflicts, and I'd imagine that Nvidia's engineers could bang out something reasonable for that in their sleep.

**Comment by oscarbg** [comment]
+1 .. Nvidia Flow 1.1 adds Vulkan support but not yet released!

**Comment by oscarbg** [comment]
maybe @apanteleev can give an answer as he is doing most commits..

**Comment by apanteleev** [comment]
The reason Flow is not included in the release version of Q2RTX is that NVIDIA does not license Flow under the terms of GPL v2. So we pre-rendered Flow’s real-time grid simulations into sprites instead.

**Comment by CKWarner** [comment]
It seems odd to have announced its release when it wasn't going to be released. Quake 2's been GPL since 2001; it shouldn't have come as a surprise. Thanks for the clarification, though.

So how about doing it in PhysX? No conflicts there. The sprites and the chunky original effects are both very limited: the chunky ones because they're from 1997 and opaque, and the sprites because they look pretty terrible anywhere other than directly at eye height. Plus there's scope to add those effects to things other than the explosions.

**Comment by SkacikPL** [comment]
Well i imagine by this point this "remaster" is considered feature complete and no major additions are planned.

**Comment by CKWarner** [comment]
[PhysX Particles & Fluid](https://developer.nvidia.com/particles) is the PhysX-accelerated equivalent of Nvidia Flow. Using it doesn't mean that they need to change the in-game physics. It's just how they'd play with particles and smoke.

**Comment by apanteleev** [comment]
> It seems odd to have announced its release when it wasn't going to be released. 

I agree the outcome is not great, sorry about that. The plans were not clear at that point; I can't comment further.

Regarding PhysX particles: they are not solving the same problem as Flow. Flow is doing volumetric combustion simulation and visualization of the results via raymarching. PhysX particles are just particle systems that can appear as sets of solid meshes or sprites. Can be used for similar kinds of effects, but not the same thing at all. Plus, it looks like particles are not included in PhysX 4.

**Comment by CKWarner** [comment]
You could still use PhysX 3.4, though. Or some other means of having better volume particle effects.

Q2RTX is specifically and pointedly a way for Nvidia engineers to show off what it's possible to do with their hardware; I'm sure there's more fun that could be had there in making cool new stuff.

**Comment by SkacikPL** [comment]
Ultimately it would be nice if it was a showcase for every tech that can be shoved in there just because they can but i'd wildly guess that at this point the project is just in maintenance mode.

**Comment by Adriaaaaan** [comment]
Would it not be possible to provide the implementation as a binary plugin?  Since the flow implementation isn't itself quake 2 could you not allow it to be delivered separately?

**Comment by SkacikPL** [comment]
It would still mean parts of the API would need to be exposed, which would make NVIDIA unhappy.

**Comment by Adriaaaaan** [comment]
Nah not at all (obviously it's a lot more complex than this) but in the
most simplistic terms you could just create a wrapper api.  That's just
particles.createExplosion(x,y).    Yeah I know it's probably really
complicated, it's just a shame because it looks so cool and is something
Nvidia had been teasing for years.

**Comment by apanteleev** [comment]
I'm not really qualified to discuss such legal issues, but options like a binary plugin have been discussed internally. We've been told by the legal team that it would still expose FLOW to GPL, so it doesn't really solve anything, just complicates things. 

What would work though is if someone else (not NVIDIA) were to integrate FLOW into Q2RTX, maybe with our guidance. Merging that back into our version could be tricky, but an independent fork can totally do that.

**Comment by SkacikPL** [comment]
> What would work though is if someone else (not NVIDIA) were to integrate FLOW into Q2RTX, maybe with our guidance. Merging that back into our version could be tricky, but an independent fork can totally do that.

I imagine that's still violation of GPL license and "purists" would complail, although i imagine as NVIDIA would be only right holding party would not take any legal action it would be a convenient impasse.

I guess it's encouraging as long as someone competent enough to both implement it and make a pure C wrapper stumbles in here.
