### ISSUE TITLE
Input from cinematics gets into the game

### ISSUE THREAD

**Issue by apanteleev** [NVIDIA/Q2RTX#337]
When you skip a cinematic, the key you used to skip it is processed as the first input in the game. For example, skip it with space, and the character will jump when map loads.

I noticed this new behavior after this PR https://github.com/NVIDIA/Q2RTX/pull/328 (Sync with Q2PRO: Game changes)
Does not reproduce before it.

@res2k can you take a look please?

**Comment by res2k** [comment]
I narrowed down the culprit to f6d22029c21194f149b70b89b621b07d74ab7832.
It looks like actions were always forwarded/processed, just that they didn't have a (visible) effect.
I addressed by explicitly not producing a command when skipping a cinematic: #338

**Comment by res2k** [comment]
@apanteleev, there are two flavors of a fix:
* 6cf8c048f71f45ec79fa861be25fce9588b37211 - What I came up with, before being made aware of ...
* 8afce9e8ba84aa90f0451160f8399ffbe452b597, the fix for that in upstream.

Both do essentially the job, but it appears to me as if the "upstream" change is somewhat sensitive ("lightly tapping" skips the cinematic, but holding a key beyond that seems to trigger the action after all)... Maybe, if you have time, give both a try and let me know which behavior you prefer.

**Comment by apanteleev** [comment]
Thanks! I think the upstream solution is fine. I just cherry-picked it into `master`.
