### ISSUE TITLE
Exposure compensation affecting particle effects/sprites

### ISSUE THREAD

**Issue by Beilerbey** [NVIDIA/Q2RTX#42]
I will start by saying that I'm no programmer so bear with me if I sound like a noob, I am.
I've noticed that the exposure compensation is incorrectly affecting the particle sprites (?), an effect that is especially noticeable with big sprites such as those of the BFG or explosions which become washed out instead of actually dimming in the more exposed areas. 
I suppose this is due to the images having a low dynamic range and the highlights being overexposed in the first place, so when the exposure goes down the highlights simply become grey instead of getting smaller as it would happen in reality. 

I imagine it would be hard/impractical to use HDR images for those sprites but I wonder if they can be excluded from the exposure compensation. Here is an image showing what I see and what I would expect: https://imgur.com/a/0ab24wE (2nd and 3rd image, please ignore the colored blobs, it's an experimental fork but the issue is the same in the original).

**Comment by SkacikPL** [comment]
It's very noticeable with blood particles where they become entirely invisible under direct sunlight.

**Comment by DU-jdto** [comment]
(To avoid confusion - 'Very High' is just 'High' but with direct light sampling on the second bounce, so it has no bearing on the issue being reported)

**Comment by apanteleev** [comment]
The problem is that the sprites and other effects are unlit, they have constant brightness. So when you are under direct sunlight, the tone mapper compensates by reducing the exposure, which makes sprites dimmer. 

I figured out a very simple workaround for this: use the average luminance from the tone mapper to control the brightness of these effects. Submitted to the `sprite-brightness` branch - let me know what you think. Looks good IMO. https://github.com/NVIDIA/Q2RTX/commit/d0b583d028405eee2b65ba95308484106740650b

**Comment by Beilerbey** [comment]
Yes, definitely much better, thanks a lot!

**Comment by SkacikPL** [comment]
I like this change a lot, it makes all particles more vibrant and close to original feel.
It also makes blood actually visible in exteriors which is a big improvement to me.

**Comment by apanteleev** [comment]
Thanks for the feedback - the change is now in master.
