### ISSUE TITLE
Light list sampling

### ISSUE THREAD

**Issue by DU-jdto** [NVIDIA/Q2RTX#44]
The light proxies used in sample_light_list often aren't a great approximation of the corresponding lights. To demonstrate this, I have taken two reference mode screenshots using pt_bump_scale 0 and pt_roughness_override 0.02:

Reflections using the light list proxies (forced via pt_direct_roughness_threshold 0):
![quake164](https://user-images.githubusercontent.com/6344802/64096357-f26fc600-cd50-11e9-9a62-3a23e9597962.png)

Reflections using the actual emissive maps (through indirect bounce specular):
![quake165](https://user-images.githubusercontent.com/6344802/64096361-f7cd1080-cd50-11e9-8052-40430c9b6260.png)

The proxies are good enough for importance sampling, but it may make sense to sample the emissive texture to get the actual light color to return. Whether that's done or not, it would probably make sense to change the proxy sizes to better match the dimensions of the emissive portions of the corresponding lights (assuming this can be done without too much difficulty, I haven't looked much into the relevant code yet).

**Comment by apanteleev** [comment]
The proxies are derived from emissive meshes in the BSP, and these meshes are intersected with boxes that represent the actual non-black part of the emissive texture. See function `collect_ligth_polys` in `bsp_mesh.c`. They may be a bit conservative on these lamps because the emissive texture has a falloff, which it shouldn't really have. On some other lamps, the emissive texture has multiple segments with dark fixture between them, and this algorithm doesn't take that into account. So, replacing the average lamp color (which is also derived from the texture) with the actual texture sampling can easily be done at the cost of some noise that will appear when the proxy is larger than the emissive part of the texture. I think the accuracy difference is not worth it though.
