### ISSUE TITLE
v1.2 issues

### ISSUE THREAD

**Issue by DU-jdto** [NVIDIA/Q2RTX#48]
1. The user "[clanramrod] MAVEDICK" on the Steam forums noticed that this pipe in the Outlands (strike) campaign map didn't look right. Upon further investigation, it appears to have backfacing normals:

![quake010](https://user-images.githubusercontent.com/6344802/69772753-b352e480-1188-11ea-8eb3-f537110fa3fe.png)

![quake011](https://user-images.githubusercontent.com/6344802/69772758-b8b02f00-1188-11ea-90f9-a0e5b9643714.png)

Both images were taken with pt_num_bounce_rays 1, flt_scale_spec 0 and flt_scale_lf 0, with the time of day set to noon (so the sun is directly overhead). The only difference is that the second image uses pt_bump_scale 0. Furthermore, adding a line to get_material which replaces the normal with the geo_normal when the normal is backfacing (dot(normal, geo_normal) < 0) has more or less the same effect as pt_bump_scale 0.

2. Might not be an issue, but was the replacement of these wall textures intentional (from the Comm Center/base3 map)?

Old:
![quake000](https://user-images.githubusercontent.com/6344802/69773051-a71b5700-1189-11ea-9b9f-59d522ed61bf.png)

New:
![quake012](https://user-images.githubusercontent.com/6344802/69773068-b4384600-1189-11ea-828f-cfd62a5f9455.png)

**Comment by apanteleev** [comment]
Thank you for reporting this.

The first issue is already fixed - as noted in the [changelog](https://github.com/NVIDIA/Q2RTX/blob/master/changelog.md) for 1.2.1. I'll try to get that published soon.

The replacement of those second textures was intentional, because the original ones tried to represent a complex structure with different materials without underlying geometry, and it just looked really bad. The new texture doesn't look like the original game, but at least it's not dirty/bad.
