### ISSUE TITLE
Sprite explosions & cutscenes

### ISSUE THREAD

**Issue by maximus105** [NVIDIA/Q2RTX#61]
The game has sprite explosions. They look wrong when viewed from above. Is it possible to correct the display of these explosion sprites or improve them, as in Quake 2 XP ? Is it possible to use 3D HUD in future versions Quake 2 RTX, as in Quake 2 XP ?
![quake000](https://user-images.githubusercontent.com/58270614/71846538-7bb65100-30d3-11ea-9676-8ae8e149f605.jpg)
![quake2xp_2020_01_07_11_06_32_040](https://user-images.githubusercontent.com/58270614/71883043-3f6c0a80-313e-11ea-84c6-10db6ca06c94.png)
In version Quake 2 RTX 1.3.0 added support for cutscenes. But the initial logo clips do not appear, for example, the logo ID Software from the Idlog.cin file. Also, the initial logo clips from the additions "Ground Zero" and "The Reckoning" do not appear, although the addons are launched and cut scenes work in them.

**Comment by ValZapod** [comment]
@maximus105 Wow, you can already play "Ground Zero" and "The Reckoning"? I have already played the whole quake 2 two weaks ago, I wanna play those)) How you can play those? You need special patch or what?

**Comment by apanteleev** [comment]
Q2XP sprites look more correct from above because they are always facing the camera, as in, parallel to the view plane. That works for them because the sprites are more... round in shape, sort of, and disappear quicker. In Q2RTX, the BFG sprites are oriented the same way. But if you try to align our cloud-style sprites to the view plane, they don't look right anymore. It's a compromise. You can see what the other option looks like if you remove this line: https://github.com/NVIDIA/Q2RTX/blob/fd239d3cdfa4eabae3af56308ca6936227fe6d5f/src/client/tent.c#L124

3D HUD is pointless, IMO.

Intro (pre-menu) videos are not implemented, and they don't really contribute anything to the gameplay. Most people would just click through them anyway.

Mission packs are not officially supported, there are some licensing issues around them. But you can build the game libraries from another source port, I think Yamagi works as-is. Besides gameplay code,  someone needs to go through the materials and maps and adjust lighting. See here for example: https://steamcommunity.com/app/1089130/discussions/0/1740010344364403145/

**Comment by maximus105** [comment]
> @ maximus105 Ого, ты уже можешь играть в "Ground Zero" и "The Reckoning"? Я уже играл весь Quake 2 два слабых назад, я хочу сыграть в них)) Как вы можете играть в них? Вам нужен специальный патч или что?

No, a patch is not needed. These addons are launched as usual through shortcuts. In Quake 2 RTX 1.3.0 introduced support for these addons.

**Comment by ValZapod** [comment]
@maximus105 А поподробнее? Прям совсем для идиотов))

**Comment by maximus105** [comment]
> @maximus105 А поподробнее? Прям совсем для идиотов))

https://www.old-games.ru/forum/threads/quake-2.21165/

**Comment by apanteleev** [comment]
> https://www.old-games.ru/forum/threads/quake-2.21165/

В целом да, но нужно собрать или найти собранные 64-битные game dll (gamex86_64.dll), иначе геймплей будет сломан. И освещение для экспанжн паков никто тоже не настраивал.

**Comment by Beilerbey** [comment]
@apanteleev Sorry if I write here but I didn't want to open an issue for a couple of questions and I wouldn't know where else to ask this:
1 - Would it be possible to integrate FOV controls in the accumulated rendering mode as they exist for the gameplay, maybe adding cylindrical projection as well?

2 - Would it be theoretically feasible to make an hybrid raster+RTX version of Quake II instead of purely PT? I'm asking because that's what I tought it would happen when Quake II RTX was first announced and I'm left with the curiosity to know how if would perform and look compared to both the original Quake II and Quake II RTX.

Thanks a lot in advance.

**Comment by apanteleev** [comment]
> Would it be possible to integrate FOV controls in the accumulated rendering mode as they exist for the gameplay, maybe adding cylindrical projection as well?

There is FOV control: right mouse button + move up/down.

> Would it be theoretically feasible to make an hybrid raster+RTX version of Quake II instead of purely PT?

Feasible? Absolutely. There is a pretty broad spectrum of possible combinations. But that probably is not something we're going to do.

**Comment by Beilerbey** [comment]
Awesome, thanks for the reply.
Hybrid rendering: sure, I wouldn't expect you to redo the whole thing, also because it doesn't seem necessary at all, but I was just wondering if there were technical limitations. Thanks again.

**Comment by maximus105** [comment]
Возможно ли в следующих версиях добавить в игру фонарик, как в Quake 2 XP ? Так как ночью на картах очень темно и неудобно все время переключаться на flare gun. Играть с фонариком ночью было бы намного удобнее.

**Comment by apanteleev** [comment]
> Возможно ли в следующих версиях добавить в игру фонарик, как в Quake 2 XP ?

Технически возможно, но качественный фонарик сделать не очень просто. То есть, повесить сферический источник света примерно около игрока - просто, и вроде бы какой-то форк это добавлял. Но для правильного фонарика нужен направленный источник, лучше с текстурой, а это пока не поддерживает рендерер. Кроме того, нужна какая-то адекватная геометрия и анимации, чтобы этот фонарик представить в first person и third person видах. Та же проблема с muzzle flashes.

**Comment by sherief** [comment]
> Возможно ли в следующих версиях добавить в игру фонарик, как в Quake 2 XP ? Так как ночью на картах очень темно и неудобно все время переключаться на flare gun. Играть с фонариком ночью было бы намного удобнее.

Check out this pull request which adds a command to swap between the flare gun and your current weapon - I bind it to my mouse's side buttons so in a dark area I swap to flare gun, shoot a flare, then swap back to my weapon

https://github.com/NVIDIA/Q2RTX/pull/63
