### ISSUE TITLE
Question: DLSS 2.0 in Q2RTX?

### ISSUE THREAD

**Issue by Beilerbey** [NVIDIA/Q2RTX#68]
Sorry if this is not the right place to ask, but would it be possible to see DLSS 2.0 running on this game? If not, any specific reason as to why (e.g. not worth it, unpractical, unfeasible, etc.)? Thanks a lot.

**Comment by adojck** [comment]
I'm also interested. Would be nice to have DLSS 2.0 in Quake 2 RTX

**Comment by apanteleev** [comment]
Technically it should be possible, but unfortunately we can't integrate DLSS 2.0 here because of the GPL restrictions. Same as FLOW.

**Comment by Beilerbey** [comment]
Got you, didn't think about that, thanks a lot for the reply!

**Comment by CKWarner** [comment]
> Technically it should be possible, but unfortunately we can't integrate DLSS 2.0 here because of the GPL restrictions. Same as FLOW.

Both technologies are Nvidia's to use as they choose, of course, but including a GPL implementation in Q2RTX would only mean that those implementations could be used in other GPL projects; the implementations behind Nvidia's other licences/NDAs/whatever would carry on unchanged. Dual-licensing technologies is a pretty standard practice.

**Comment by apanteleev** [comment]
> including a GPL implementation in Q2RTX would only mean that those implementations could be used in other GPL projects

DLSS would have to be open source in this case. That's the problem.

**Comment by CKWarner** [comment]
> DLSS would have to be open source in this case. That's the problem.

The implementation of DLSS in Q2RTX would have to be open source. The implementation of DLSS in whatever else would be whatever licence you wanted.

**Comment by apanteleev** [comment]
The implementation of DLSS, currently, is a black box library / DLL. It can be integrated into games as is, by linking to that library through the SDK. But, if Nvidia were to integrate it into Q2RTX or any other GPL project, that library would have to be open sourced under GPL as well. And that's just not going to happen.

**Comment by Goddard** [comment]
> 
> 
> The implementation of DLSS, currently, is a black box library / DLL. It can be integrated into games as is, by linking to that library through the SDK. But, if Nvidia were to integrate it into Q2RTX or any other GPL project, that library would have to be open sourced under GPL as well. And that's just not going to happen.

Where is the library? I can't find information on how to use it.   Thanks.  A plugin outside the project could deal with all the problems.

**Comment by XakepSDK** [comment]
Can be DLSS under build flag? So people could compile with DLSS, while NVIDIA will distribute without DLSS.

**Comment by Goddard** [comment]
I've later found out Nvidia is pretty strict with this library.  You need to get a special code just to use it in UE4.  I was thinking that maybe it could just be easily added to any CUDA/OpenGL, or something game.  Am I correct in this?

**Comment by perfectcolors** [comment]
I really hope a way can be found to implement some form of DLSS into Q2RTX for performance reasons to make this less of a tech demo and promotion of Nvidia tech and more of a playable version of Q2.

id Software / John Carmack open sourced cutting edge technology of its era in order to benefit others, it feels like such a shame to be held back here especially when this work is being used to showcase advancements in 3D graphics.

**Comment by Beilerbey** [comment]
@apanteleev I read somewhere, related to UE4 DLSS branch if I'm not mistaken, that in order to gain access to the DLSS libraries one needs to submit a valid project to be evaluated by Nvidia. Does this procedure apply to Quake II RTX as well? Given that it is an Nvidia project I would guess that it would be "approved" by default, correct? Since @Goddard seems willing to make it happen (if that's the case, thank you!) I was wondering what the appropriate procedure would be. Thank you in advance.

**Comment by JonasNo** [comment]
@apanteleev  Oh boy. You can't help yourself can you? Let me teach you about what happens when you use a beloved open source game. I've seen this before. You're begging people to reverse engineer the DLSS. You better be careful. You have the chance to put a license on it now. When it's reverse engineered it's open season. No chance what so ever to undo it nor put a license on it nor try to put the genie back in the bottle through censorship. You must be very new at this open source thing. And of all the games you chose Quake 2. I'm predicting DLSS will be reverse engineered soon. You simply do not deny Quake fans when you yourself have opened the door to tease them and then to deny them the full experience. They are extremely talented.

**Comment by vityafx** [comment]
Now both are accessible and available (flow and dlss). Are there any plans on integrating those yet?

**Comment by apanteleev** [comment]
Neither Flow nor DLSS are available as open source. The recent change in DLSS availability to more developers doesn't really change anything regarding Q2RTX and its license requirements.

**Comment by vityafx** [comment]
> Neither Flow nor DLSS are available as open source. The recent change in DLSS availability to more developers doesn't really change anything regarding Q2RTX and its license requirements.

Yes, sorry, I misinterpreted the news. That's unfortunate to hear. Thanks.

**Comment by JohnChristmann** [comment]
I realize it's been nearly two years since this has been looked at but something that's been done with a number of other RT/PT projects is implementing DLSS but just not including the DLL file with the project - users must provide the file themselves.  Would this not work around the open source requirement issue?
