### ISSUE TITLE
Unable to launch on Linux

### ISSUE THREAD

**Issue by echozio** [NVIDIA/Q2RTX#95]
Launch log: https://gist.github.com/chris-echoz/38944ac9800fdd9a60bb7fb6ded3433e

Running Debian Sid, kernel 5.9, Nvidia 455.45.01.
I have an RTX 3080, and no issues running other Vulkan applications.

The game would fail to run with the same error when I had a GTX 1060 (6 GB), but I always assumed this was due to lack of RTX support.

**Comment by melonlm** [comment]
Same here.
Debian SID, kernel: 5.10.4-xanmod1, Nvidia driver: 460.32.03, also tested with 455.45.01, with same result.

I should mention it has been running before, Q2RTX 1.02, with older, non-RTX card (1660 Ti), and older driver. Unfortunately I cannot pinpoint when it got borked.

**Comment by chris-echoz** [comment]
Thank god I'm not alone. 460.32.03 also didn't fix this for me.

**Comment by jksiazek** [comment]
Had the exact same issue, Debian Testing, found out the default NVIDIA installer on debian does not include the ray tracing libraries. Install libnvidia-cbl and libnvidia-rtcore, fixes this right up

**Comment by melonlm** [comment]
> Had the exact same issue, Debian Testing, found out the default NVIDIA installer included with the distribution on debian does not include the ray tracing libraries. Install libnvidia-cbl and libnvidia-rtcore, fixes this right up

Unfortunately that was not it for me. I had both of those installed.

In desperation I went digging deeper. Without much hope I ran "strace" on the game binary. I have noticed that just before throwwing the error it tried to open the Cuda library, but instead of going the system way (libcuda.so, or libcuda.so.1). it went straight for specific version (currently libcuda.so.460.39) which was not available in the paths, as it is governed by Debian's alternatives system and tucked away in package specific dierctory (/usr/lib/x86_64-linux-gnu/nvidia/current/libcuda.so.460.39)

As a workaround i did: sudo ln -s /usr/lib/x86_64-linux-gnu/nvidia/current/libcuda.so.460.39 /usr/lib/x86_64-linux-gnu/libcuda.so.460.39

I intend to file a bug with Debian once confirmed that this is not a fault in my specific installation.

**Comment by chris-echoz** [comment]
On Fri, Feb 19, 2021 at 01:17:51AM -0800, melonlm wrote:
> > Had the exact same issue, Debian Testing, found out the default NVIDIA installer included with the distribution on debian does not include the ray tracing libraries. Install libnvidia-cbl and libnvidia-rtcore, fixes this right up
> 
> Unfortunately that was not it for me. I had both of those installed.
> 
> In desperation I went digging deeper. Without much hope I ran "strace" on the game binary. I have noticed that just before throwwing the error it tried to open the Cuda library, but instead of going the system way (libcuda.so, or libcuda.so.1). it went straight for specific version (currently libcuda.so.460.39) which was not available in the paths, as it is governed by Debian's alternatives system and tucked away in package specific dierctory (/usr/lib/x86_64-linux-gnu/nvidia/current/libcuda.so.460.39)
> 
> As a workaround i did: sudo ln -s /usr/lib/x86_64-linux-gnu/nvidia/current/libcuda.so.460.39 /usr/lib/x86_64-linux-gnu/libcuda.so.460.39
> 
> I intend to file a bug with Debian once confirmed that this is not a fault in my specific installation.
> 

This fixed it for me.

-- 
Chris

**Comment by ignapk** [comment]
I had the same issue on Fedora, and it turned out to be a problem with libcuda as well, though in my case it was simply missing altogether - installing it manually with `sudo dnf install xorg-x11-drv-nvidia-cuda` fixed it.
